/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ControleConta;
import controle.ControleUsuario;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Conta;
import modelo.Usuario;

/**
 *
 * @author Kelvin
 */
public class ContaPrincipal extends javax.swing.JDialog {

    /**
     * Creates new form Usuario
     */
    public ContaPrincipal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tabela();
    }

    public void tabela() {
        ControleConta conC = new ControleConta();
        ControleUsuario conU = new ControleUsuario();
        ArrayList<Conta> c = conC.getContas();
        Usuario u = new Usuario();
        DefaultTableModel modelo = (DefaultTableModel) tbConta.getModel();
        int t = modelo.getRowCount();
        for (int i = 0; i < t; i++) {
            modelo.removeRow(0);
        }

        Date data = new Date(System.currentTimeMillis());

        for (int i = 0; i < c.size(); i++) {
            String v[] = new String[7];
            v[0] = c.get(i).getIdConta() + "";
            v[1] = c.get(i).getNome();
            u = conU.getUsuario(c.get(i).getIdUsuario());
            v[2] = u.getNome();
            v[3] = "R$:" + c.get(i).getValor();
            v[4] = c.get(i).getDataVencimentoFormatado();
            v[5] = String.valueOf(data);
            if (c.get(i).isPago()) {
                v[6] = "Pago";
            } else {
                v[6] = "Pendente";
            }
            modelo.addRow(v);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pConta = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        btRelatorioM = new javax.swing.JButton();
        btRelatorioA = new javax.swing.JButton();
        btCadastrar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btDesativar = new javax.swing.JButton();
        btPagar = new javax.swing.JButton();
        btDetalhes = new javax.swing.JButton();
        cbAno = new javax.swing.JComboBox();
        cbMes = new javax.swing.JComboBox();
        spConta = new javax.swing.JScrollPane();
        tbConta = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbTitulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbTitulo.setText(" Gerenciar Histórico de Contas");

        btRelatorioM.setText("Gerar Relatório do Mês");
        btRelatorioM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelatorioMActionPerformed(evt);
            }
        });

        btRelatorioA.setText("Gerar Relatório Anual");
        btRelatorioA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btRelatorioA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelatorioAActionPerformed(evt);
            }
        });

        btCadastrar.setText("Cadastrar");
        btCadastrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btAlterar.setText("Alterar");
        btAlterar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btDesativar.setText("Remover");
        btDesativar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btDesativar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDesativarActionPerformed(evt);
            }
        });

        btPagar.setText("Pagar Conta");
        btPagar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPagarActionPerformed(evt);
            }
        });

        btDetalhes.setText("Detalhes");
        btDetalhes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDetalhesActionPerformed(evt);
            }
        });

        cbAno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015" }));

        cbMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));

        tbConta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Conta", "Responsável", "Valor", "Vencimento", "Data Pagamento", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbConta.getTableHeader().setReorderingAllowed(false);
        spConta.setViewportView(tbConta);
        if (tbConta.getColumnModel().getColumnCount() > 0) {
            tbConta.getColumnModel().getColumn(0).setResizable(false);
            tbConta.getColumnModel().getColumn(0).setPreferredWidth(5);
            tbConta.getColumnModel().getColumn(1).setResizable(false);
            tbConta.getColumnModel().getColumn(2).setResizable(false);
            tbConta.getColumnModel().getColumn(3).setResizable(false);
            tbConta.getColumnModel().getColumn(4).setResizable(false);
            tbConta.getColumnModel().getColumn(5).setResizable(false);
            tbConta.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout pContaLayout = new javax.swing.GroupLayout(pConta);
        pConta.setLayout(pContaLayout);
        pContaLayout.setHorizontalGroup(
            pContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pContaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pContaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pContaLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btRelatorioA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btDesativar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btAlterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btRelatorioM, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pContaLayout.createSequentialGroup()
                                .addComponent(cbAno, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(spConta))))
                .addGap(25, 25, 25))
        );
        pContaLayout.setVerticalGroup(
            pContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pContaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pContaLayout.createSequentialGroup()
                        .addGroup(pContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pContaLayout.createSequentialGroup()
                        .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btDesativar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btRelatorioA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btRelatorioM, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(866, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btRelatorioMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelatorioMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btRelatorioMActionPerformed

    private void btRelatorioAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelatorioAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btRelatorioAActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        ContaCadastro cC = new ContaCadastro();
        JDialog cCD = new JDialog(cC, rootPaneCheckingEnabled);
        cC.tipo = 0;
        cCD.setBounds(cC.getBounds());
        cCD.add(cC.getContentPane());
        cCD.setTitle("Cadastrar Conta");
        cCD.setResizable(false);
        cCD.setVisible(true);
        tabela();
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        if (tbConta.getSelectedRow() != -1) {
            ControleConta conC = new ControleConta();
            Conta c = conC.getConta(Integer.parseInt(tbConta.getValueAt(tbConta.getSelectedRow(), 0) + ""));
            ContaCadastro cC = new ContaCadastro();

            cC.tipo = c.getIdConta();
            cC.txtConta.setText(c.getNome());
            cC.ftxtValor.setText(c.getValor() + "");
            cC.txtData.setText(c.getDataVencimentoFormatado());
            cC.lbTitulo.setText("Alterar Conta");
            cC.btCadastrar.setText("Alterar");
            if (c.isIsFixo()) {
                cC.rbFixo.setSelected(true);
            } else {
                cC.rbVariavel.setSelected(true);
            }
            JDialog cUD = new JDialog(cC, rootPaneCheckingEnabled);
            cUD.setBounds(cC.getBounds());
            cUD.add(cC.getContentPane());
            cUD.setTitle("Alterar Conta");
            cUD.setResizable(false);
            cUD.setVisible(true);

            tabela();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um item da tabela primeiro!", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btDesativarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDesativarActionPerformed
        if (tbConta.getSelectedRow() != -1) {
            ControleConta conC = new ControleConta();
            Conta c = conC.getConta(Integer.parseInt(tbConta.getValueAt(tbConta.getSelectedRow(), 0) + ""));
            if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja remover esta conta?\n", "Confirmar", JOptionPane.YES_NO_OPTION) == 0) {
                conC.removerConta(c);
                JOptionPane.showMessageDialog(null, "Conta removida com sucesso!", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
            }
            tabela();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um item da tabela primeiro!", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btDesativarActionPerformed

    private void btPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btPagarActionPerformed

    private void btDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDetalhesActionPerformed
        if (tbConta.getSelectedRow() != -1) {
            ContaDetalhes cD = new ContaDetalhes();
            JDialog cDD = new JDialog(cD, rootPaneCheckingEnabled);
            
            ControleConta conC = new ControleConta();
            Conta c = conC.getConta(Integer.parseInt(tbConta.getValueAt(tbConta.getSelectedRow(), 0) + ""));

            cD.txtConta.setText(c.getNome());
            cD.ftxtValor.setText(c.getValor() + "");
            cD.txtData.setText(c.getDataVencimentoFormatado());
            
            cDD.setBounds(cD.getBounds());
            cDD.add(cD.getContentPane());
            cDD.setTitle("Detalhes da Conta");
            cDD.setResizable(false);
            cDD.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um item da tabela primeiro!", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btDetalhesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ContaPrincipal dialog = new ContaPrincipal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btDesativar;
    private javax.swing.JButton btDetalhes;
    private javax.swing.JButton btPagar;
    private javax.swing.JButton btRelatorioA;
    private javax.swing.JButton btRelatorioM;
    private javax.swing.JComboBox cbAno;
    private javax.swing.JComboBox cbMes;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel pConta;
    private javax.swing.JScrollPane spConta;
    private javax.swing.JTable tbConta;
    // End of variables declaration//GEN-END:variables
}
