/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ControleConta;
import controle.ControleUsuario;
import javax.swing.JOptionPane;
import modelo.Conta;

/**
 *
 * @author Kelvin
 */
public class ContaCadastro extends javax.swing.JFrame {

    public int tipo;

    /**
     * Creates new form ContaCadastro
     */
    public ContaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgTipo = new javax.swing.ButtonGroup();
        pContaCadastro = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        lbConta = new javax.swing.JLabel();
        lbValor = new javax.swing.JLabel();
        lbData = new javax.swing.JLabel();
        lbFoto = new javax.swing.JLabel();
        lbImagem = new javax.swing.JLabel();
        txtConta = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        txtFoto = new javax.swing.JTextField();
        ftxtValor = new javax.swing.JFormattedTextField();
        btCadastrar = new javax.swing.JButton();
        btFoto = new javax.swing.JButton();
        lbValor1 = new javax.swing.JLabel();
        rbFixo = new javax.swing.JRadioButton();
        rbVariavel = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Conta");
        setName("CadastrarConta"); // NOI18N
        setPreferredSize(new java.awt.Dimension(550, 260));

        pContaCadastro.setPreferredSize(new java.awt.Dimension(550, 260));

        lbTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbTitulo.setText("Cadastrar Conta");

        lbConta.setText("Nome da conta:");
        lbConta.setMaximumSize(new java.awt.Dimension(71, 20));
        lbConta.setMinimumSize(new java.awt.Dimension(71, 20));
        lbConta.setPreferredSize(new java.awt.Dimension(71, 20));

        lbValor.setText("Valor (R$):");
        lbValor.setMaximumSize(new java.awt.Dimension(28, 20));
        lbValor.setMinimumSize(new java.awt.Dimension(28, 20));
        lbValor.setPreferredSize(new java.awt.Dimension(28, 20));

        lbData.setText("Data de Vencimento:");
        lbData.setMaximumSize(new java.awt.Dimension(100, 20));
        lbData.setMinimumSize(new java.awt.Dimension(100, 20));
        lbData.setPreferredSize(new java.awt.Dimension(100, 20));

        lbFoto.setText("Foto:");
        lbFoto.setMaximumSize(new java.awt.Dimension(26, 20));
        lbFoto.setMinimumSize(new java.awt.Dimension(26, 20));
        lbFoto.setPreferredSize(new java.awt.Dimension(26, 20));

        txtFoto.setEnabled(false);

        ftxtValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btFoto.setText(" ... ");

        lbValor1.setText("Tipo:");
        lbValor1.setMaximumSize(new java.awt.Dimension(28, 20));
        lbValor1.setMinimumSize(new java.awt.Dimension(28, 20));
        lbValor1.setPreferredSize(new java.awt.Dimension(28, 20));

        bgTipo.add(rbFixo);
        rbFixo.setSelected(true);
        rbFixo.setText("Fixo");
        rbFixo.setPreferredSize(new java.awt.Dimension(93, 20));
        rbFixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFixoActionPerformed(evt);
            }
        });

        bgTipo.add(rbVariavel);
        rbVariavel.setText("Variável");
        rbVariavel.setPreferredSize(new java.awt.Dimension(93, 20));
        rbVariavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVariavelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pContaCadastroLayout = new javax.swing.GroupLayout(pContaCadastro);
        pContaCadastro.setLayout(pContaCadastroLayout);
        pContaCadastroLayout.setHorizontalGroup(
            pContaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pContaCadastroLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pContaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pContaCadastroLayout.createSequentialGroup()
                        .addComponent(txtFoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pContaCadastroLayout.createSequentialGroup()
                        .addGroup(pContaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTitulo)
                            .addGroup(pContaCadastroLayout.createSequentialGroup()
                                .addGroup(pContaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lbFoto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .addComponent(lbValor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbConta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbValor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pContaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pContaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtConta, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                        .addComponent(ftxtValor)
                                        .addComponent(txtData))
                                    .addGroup(pContaCadastroLayout.createSequentialGroup()
                                        .addComponent(rbFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbVariavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addComponent(lbImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pContaCadastroLayout.setVerticalGroup(
            pContaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pContaCadastroLayout.createSequentialGroup()
                .addGroup(pContaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pContaCadastroLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lbTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pContaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pContaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbVariavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pContaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftxtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pContaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pContaCadastroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pContaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btFoto)
                    .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pContaCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pContaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 253, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        ControleConta cConta = new ControleConta();
        ControleUsuario cU = new ControleUsuario();
        Conta conta = new Conta();

        conta.setNome(txtConta.getText());
        conta.setValor(Double.parseDouble(ftxtValor.getText().replace(',', '.')));
        conta.setDataVencimento(txtData.getText());
        conta.setIdUsuario(cU.getLogado().getIdUsuario());
        if (cConta.validarConta(conta)) {
            conta.setDataVencimentoFormatado(txtData.getText());
            if (rbVariavel.isSelected()) {
                conta.setIsFixo(false);
            } else if (rbFixo.isSelected()) {
                conta.setIsFixo(true);
            }
            if (tipo == 0) {
                cConta.adicionarConta(conta);
                JOptionPane.showMessageDialog(null, "Conta cadastrada com sucesso!");
            }else {
                conta.setIdConta(tipo);
                cConta.alterarConta(conta);
                JOptionPane.showMessageDialog(null, "Conta alterada com sucesso!");
            }
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Existem campos inválidos!",
                    "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void rbFixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFixoActionPerformed
        ftxtValor.setEnabled(false);
        txtData.setEnabled(false);
    }//GEN-LAST:event_rbFixoActionPerformed

    private void rbVariavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVariavelActionPerformed
        ftxtValor.setEnabled(true);
        txtData.setEnabled(true);
    }//GEN-LAST:event_rbVariavelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgTipo;
    public javax.swing.JButton btCadastrar;
    private javax.swing.JButton btFoto;
    public javax.swing.JFormattedTextField ftxtValor;
    private javax.swing.JLabel lbConta;
    private javax.swing.JLabel lbData;
    private javax.swing.JLabel lbFoto;
    private javax.swing.JLabel lbImagem;
    public javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbValor;
    private javax.swing.JLabel lbValor1;
    private javax.swing.JPanel pContaCadastro;
    public javax.swing.JRadioButton rbFixo;
    public javax.swing.JRadioButton rbVariavel;
    public javax.swing.JTextField txtConta;
    public javax.swing.JTextField txtData;
    private javax.swing.JTextField txtFoto;
    // End of variables declaration//GEN-END:variables
}
